name = "signer"
main = "src/cloudflare/index.es6.ts"
compatibility_date = "2023-03-04"

[build]
# We need to first produce a npm package at internal-crypto-wasm/pkg containing a WASM glue and a WASM module,
# and then wrangler can bundle everything (into an es6 module) starting at src/index.cloudflare-es6.ts.
command = "npm run build-internal-crypto-wasm"
